final doctorMapList = [
  {
    "firstName": "David",
    "lastName": "Kemp",
    "type": "Heart Surgeon",
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isFavourite": true,
    "image": "assets/doctor.png",
    "id": "1",
    "location": "St. John's",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "firstName": "Kathy",
    "lastName": "Mathews",
    "type": "Neurologist",
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isFavourite": false,
    "image": "assets/doctor_4.png",
    "id": "2",
    "location": "Mount Pearl",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "firstName": "Morris",
    "lastName": "Terry",
    "type": "Cardio Surgeon",
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isFavourite": false,
    "image": "assets/doctor_3.png",
    "id": "3",
    "location": "Gander",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "firstName": "Bruce",
    "lastName": "Banner",
    "type": "Heart Surgeon",
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isFavourite": true,
    "image":"assets/doctor_1.png",
    "id": "4",
    "location": "Paradise",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  }
];