import 'package:health_mate/models/prescription.dart';

final doctorMapList = [
  {
    "name": "David Kemp",
    "specialization": "Heart Surgeon",
    "medicalId": "",
    "researchPaperURL": "",
    "dateOfBirth": '2023-12-01T15:30:00',
    "chatIds": [],
    "rating": 4,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isFavourite": true,
    "image": "assets/doctor.png",
    "id": "1",
    "location": "St. John's",
    "description":
        "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Kathy Mathews",
    "specialization": "Neurologist",
    "medicalId": "",
    "researchPaperURL": "",
    "dateOfBirth": '2023-12-01T15:30:00',
    "chatIds": [],
    "rating": 3,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isFavourite": false,
    "image": "assets/doctor_4.png",
    "id": "2",
    "location": "Mount Pearl",
    "description":
        "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Morris Terry",
    "specialization": "Cardio Surgeon",
    "medicalId": "",
    "researchPaperURL": "",
    "dateOfBirth": '2023-12-01T15:30:00',
    "chatIds": [],
    "rating": 2,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isFavourite": false,
    "image": "assets/doctor_3.png",
    "id": "3",
    "location": "Gander",
    "description":
        "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Bruce Banner",
    "specialization": "Heart Surgeon",
    "medicalId": "",
    "researchPaperURL": "",
    "dateOfBirth": '2023-12-01T15:30:00',
    "chatIds": [],
    "rating": 1,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isFavourite": true,
    "image": "assets/doctor_1.png",
    "id": "4",
    "location": "Paradise",
    "description":
        "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  }
];

final patientMapList = [
  {
    'fname': 'Jack',
    'lname': 'Morris',
    'dob': DateTime(1986, 7, 1),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B7N0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'B+',
    'eyeCol': 'Brown',
    'skinTone': 'White',
    'email': 'rohit@test.com',
    'phone': '709-997-8666',
    'chatIds': [],
    'photoUri': 'assets/user_1.png',
    'isDoctor': false,
  },
  {
    'fname': 'Karina',
    'lname': 'Karson',
    'dob': DateTime(1984, 6, 27),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B9N0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'O-',
    'eyeCol': 'Blue',
    'skinTone': 'White',
    'email': 'pat@test.com',
    'phone': '709-997-8111',
    'chatIds': [],
    'photoUri': 'assets/user_2.png',
    'isDoctor': false,
  },
  {
    'fname': 'Rob',
    'lname': 'Smith',
    'dob': DateTime(1981, 6, 18),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B7K0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Blonde',
    'bloodType': 'B+',
    'eyeCol': 'Blue',
    'skinTone': 'White',
    'email': 'smith@test.com',
    'phone': '709-997-8566',
    'chatIds': [],
    'photoUri': 'assets/user_3.png',
    'isDoctor': false,
  },
  {
    'fname': 'Chris',
    'lname': 'Stuckless',
    'dob': DateTime(1989, 6, 17),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B7Y0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'B-',
    'eyeCol': 'Brown',
    'skinTone': 'White',
    'email': 'glen@test.com',
    'phone': '709-997-8766',
    'chatIds': [],
    'photoUri': 'assets/user_4.png',
    'isDoctor': false,
  },
  {
    'fname': 'John',
    'lname': 'Smith',
    'dob': DateTime(1986, 9, 7),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B7Y0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'B-',
    'eyeCol': 'Brown',
    'skinTone': 'White',
    'email': 'glen@test.com',
    'phone': '709-997-8766',
    'chatIds': [],
    'photoUri': 'assets/user_6.png',
    'isDoctor': false,
  },
  {
    'fname': 'Linda',
    'lname': 'Rideout',
    'dob': DateTime(1980, 11, 10),
    'sex': 'F',
    'addr': 'addr',
    'post': 'A1B7Y0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'B-',
    'eyeCol': 'Brown',
    'skinTone': 'White',
    'email': 'glen@test.com',
    'phone': '709-997-8766',
    'photoUri': 'assets/user_5.png',
    'chatIds': [],
    'isDoctor': false,
  }
];

final Map<String, Map<String, bool>> medicines = {
  'Aspirin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Ibuprofen': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Acetaminophen': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Amoxicillin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Lipitor': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Lisinopril': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Metformin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Amlodipine': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Levothyroxine': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Omeprazole': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Simvastatin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Gabapentin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Metoprolol': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Hydrochlorothiazide': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Losartan': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Prednisone': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Escitalopram': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Sertraline': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Albuterol': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Warfarin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
};

final List<Prescription> prescriptions = [
  Prescription(
    doctorFirstName: 'Mashoor',
    doctorLastName: 'Gulati',
    userFirstName: 'Shivam',
    userLastName: 'Grover',
    contactInfo: '123-456-7890',
    date: '2023-01-01',
    prescriptionPdfUrl:
    'https://firebasestorage.googleapis.com/v0/b/health-mate-4768.appspot.com/o/prescription.pdf?alt=media&token=5a5f9ac5-88e0-4d22-9215-a9101f4fa2fb', // Replace with the actual URL
    medicineName: 'Aspirin',
    doctorImage: 'assets/doctor_gulati.png',
    userImage: 'assets/user_1.png',
    userId: '',
    prescriptionId: '',
  ),
  Prescription(
    doctorFirstName: 'Garvit',
    doctorLastName: 'Gupta',
    userFirstName: 'Arya',
    userLastName: 'Grover',
    contactInfo: '123-456-7890',
    date: '2023-01-02',
    prescriptionPdfUrl:
    'https://firebasestorage.googleapis.com/v0/b/health-mate-4768.appspot.com/o/prescription.pdf?alt=media&token=5a5f9ac5-88e0-4d22-9215-a9101f4fa2fb', // Replace with the actual URL
    medicineName: 'Advil',
    doctorImage: 'assets/doctor.png',
    userImage: 'assets/user_2.png',
    userId:
    '', // think about making a static User class containing all the properties
    prescriptionId: '',
  ),
  Prescription(
    doctorFirstName: 'Jogan',
    doctorLastName: 'Walia',
    userFirstName: 'Simba',
    userLastName: 'Grover',
    contactInfo: '123-456-7890',
    date: '2023-04-01',
    prescriptionPdfUrl:
    'https://firebasestorage.googleapis.com/v0/b/health-mate-4768.appspot.com/o/prescription.pdf?alt=media&token=5a5f9ac5-88e0-4d22-9215-a9101f4fa2fb', // Replace with the actual URL
    medicineName: 'Viagra',
    doctorImage: 'assets/doctor_1.png',
    userImage: 'assets/user_3.png',
    userId: '',
    prescriptionId: '',
  ),
  Prescription(
    doctorFirstName: 'Vaibhav',
    doctorLastName: 'Mehra',
    userFirstName: 'Shivam',
    userLastName: 'Choudhary',
    contactInfo: '123-456-7890',
    date: '2023-04-18',
    prescriptionPdfUrl:
    'https://firebasestorage.googleapis.com/v0/b/health-mate-4768.appspot.com/o/prescription.pdf?alt=media&token=5a5f9ac5-88e0-4d22-9215-a9101f4fa2fb', // Replace with the actual URL
    medicineName: 'Ibuprofen',
    doctorImage: 'assets/doctor_3.png',
    userImage: 'assets/user_4.png',
    userId: '',
    prescriptionId: '',
  ),
  Prescription(
    doctorFirstName: 'Sawal',
    doctorLastName: 'Nijjer',
    userFirstName: 'Goku',
    userLastName: 'Grover',
    contactInfo: '123-456-7890',
    date: '2023-08-23',
    prescriptionPdfUrl:
    'https://firebasestorage.googleapis.com/v0/b/health-mate-4768.appspot.com/o/prescription.pdf?alt=media&token=5a5f9ac5-88e0-4d22-9215-a9101f4fa2fb', // Replace with the actual URL
    medicineName: 'Paracetamol',
    doctorImage: 'assets/doctor_4.png',
    userImage: 'assets/user_5.png',
    userId: '',
    prescriptionId: '',
  ),
  Prescription(
    doctorFirstName: 'Bhavesh',
    doctorLastName: 'Sahni',
    userFirstName: 'Gohan',
    userLastName: 'Grover',
    contactInfo: '123-456-7890',
    date: '2023-11-19',
    prescriptionPdfUrl:
    'https://firebasestorage.googleapis.com/v0/b/health-mate-4768.appspot.com/o/prescription.pdf?alt=media&token=5a5f9ac5-88e0-4d22-9215-a9101f4fa2fb', // Replace with the actual URL
    medicineName: 'Lipitor',
    doctorImage: 'assets/doctor.png',
    userImage: 'assets/user_6.png',
    userId: '',
    prescriptionId: '',
  ),
  Prescription(
    doctorFirstName: 'Rishab',
    doctorLastName: 'Gupta',
    userFirstName: 'Gotenks',
    userLastName: 'Grover',
    contactInfo: '123-456-7890',
    date: '2023-12-27',
    prescriptionPdfUrl:
    'https://firebasestorage.googleapis.com/v0/b/health-mate-4768.appspot.com/o/prescription.pdf?alt=media&token=5a5f9ac5-88e0-4d22-9215-a9101f4fa2fb', // Replace with the actual URL
    medicineName: 'Penicillin',
    doctorImage: 'assets/doctor_4.png',
    userImage: 'assets/user_6.png',
    userId: '',
    prescriptionId: '',
  ),
  // Add more prescriptions as needed
];