final doctorMapList = [
  {
    "firstName": "David",
    "lastName": "Kemp",
    "type": "Heart Surgeon",
    "rating": 4,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isFavourite": true,
    "image": "assets/doctor.png",
    "id": "1",
    "location": "St. John's",
    "description":
        "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "firstName": "Kathy",
    "lastName": "Mathews",
    "type": "Neurologist",
    "rating": 3,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isFavourite": false,
    "image": "assets/doctor_4.png",
    "id": "2",
    "location": "Mount Pearl",
    "description":
        "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "firstName": "Morris",
    "lastName": "Terry",
    "type": "Cardio Surgeon",
    "rating": 2,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isFavourite": false,
    "image": "assets/doctor_3.png",
    "id": "3",
    "location": "Gander",
    "description":
        "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "firstName": "Bruce",
    "lastName": "Banner",
    "type": "Heart Surgeon",
    "rating": 1,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isFavourite": true,
    "image": "assets/doctor_1.png",
    "id": "4",
    "location": "Paradise",
    "description":
        "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  }
];

final patientMapList = [
  {
    'fname': 'Jack',
    'lname': 'Morris',
    'dob': DateTime(1986, 7, 1),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B7N0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'B+',
    'eyeCol': 'Brown',
    'skinTone': 'White',
    'email': 'rohit@test.com',
    'phone': '709-997-8666',
    'chatIds': [],
    'photoUri': 'assets/user_1.png',
    'isDoctor': false,
  },
  {
    'fname': 'Karina',
    'lname': 'Karson',
    'dob': DateTime(1984, 6, 27),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B9N0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'O-',
    'eyeCol': 'Blue',
    'skinTone': 'White',
    'email': 'pat@test.com',
    'phone': '709-997-8111',
    'chatIds': [],
    'photoUri': 'assets/user_2.png',
    'isDoctor': false,
  },
  {
    'fname': 'Rob',
    'lname': 'Smith',
    'dob': DateTime(1981, 6, 18),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B7K0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Blonde',
    'bloodType': 'B+',
    'eyeCol': 'Blue',
    'skinTone': 'White',
    'email': 'smith@test.com',
    'phone': '709-997-8566',
    'chatIds': [],
    'photoUri': 'assets/user_3.png',
    'isDoctor': false,
  },
  {
    'fname': 'Chris',
    'lname': 'Stuckless',
    'dob': DateTime(1989, 6, 17),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B7Y0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'B-',
    'eyeCol': 'Brown',
    'skinTone': 'White',
    'email': 'glen@test.com',
    'phone': '709-997-8766',
    'chatIds': [],
    'photoUri': 'assets/user_4.png',
    'isDoctor': false,
  },
  {
    'fname': 'John',
    'lname': 'Smith',
    'dob': DateTime(1986, 9, 7),
    'sex': 'M',
    'addr': 'addr',
    'post': 'A1B7Y0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'B-',
    'eyeCol': 'Brown',
    'skinTone': 'White',
    'email': 'glen@test.com',
    'phone': '709-997-8766',
    'chatIds': [],
    'photoUri': 'assets/user_6.png',
    'isDoctor': false,
  },
  {
    'fname': 'Linda',
    'lname': 'Rideout',
    'dob': DateTime(1980, 11, 10),
    'sex': 'F',
    'addr': 'addr',
    'post': 'A1B7Y0',
    'city': "St. John's",
    'province': 'NL',
    'hairCol': 'Black',
    'bloodType': 'B-',
    'eyeCol': 'Brown',
    'skinTone': 'White',
    'email': 'glen@test.com',
    'phone': '709-997-8766',
    'photoUri': 'assets/user_5.png',
    'chatIds': [],
    'isDoctor': false,
  }
];

final Map<String, Map<String, bool>> medicines = {
  'Aspirin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Ibuprofen': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Acetaminophen': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Amoxicillin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Lipitor': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Lisinopril': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Metformin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Amlodipine': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Levothyroxine': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Omeprazole': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Simvastatin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Gabapentin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Metoprolol': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Hydrochlorothiazide': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Losartan': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Prednisone': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Escitalopram': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Sertraline': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Albuterol': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
  'Warfarin': {
    'Morning': false,
    'Afternoon': false,
    'Evening': false,
  },
};
