// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeJZqoZFn4W8YXZRMRxFNCx83zOvDmwYc',
    appId: '1:1005622537424:web:a20a42bcfb3c639d05c2d5',
    messagingSenderId: '1005622537424',
    projectId: 'health-mate-4768',
    authDomain: 'health-mate-4768.firebaseapp.com',
    storageBucket: 'health-mate-4768.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY9HpdAeHKpckt6N1IqX0zAmudc77H2rg',
    appId: '1:1005622537424:android:00ee01f88eacd47a05c2d5',
    messagingSenderId: '1005622537424',
    projectId: 'health-mate-4768',
    storageBucket: 'health-mate-4768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADf3tIYKO-R1mCjQOnZbV_7obuEyt4DEI',
    appId: '1:1005622537424:ios:b4faac70ca9987f105c2d5',
    messagingSenderId: '1005622537424',
    projectId: 'health-mate-4768',
    storageBucket: 'health-mate-4768.appspot.com',
    androidClientId: '1005622537424-6j5qk51aqnufgivr1t2ikag1d4h9gqv1.apps.googleusercontent.com',
    iosClientId: '1005622537424-u7jnc9jrq4u15iovnmf47lgd4svq8e08.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADf3tIYKO-R1mCjQOnZbV_7obuEyt4DEI',
    appId: '1:1005622537424:ios:40551dea6727dfb705c2d5',
    messagingSenderId: '1005622537424',
    projectId: 'health-mate-4768',
    storageBucket: 'health-mate-4768.appspot.com',
    androidClientId: '1005622537424-6j5qk51aqnufgivr1t2ikag1d4h9gqv1.apps.googleusercontent.com',
    iosClientId: '1005622537424-4f4rea2h5vi7akdahbimon7svkmq907p.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMate.RunnerTests',
  );
}
